name: smart-core/default
title: Тема по умолчанию
developer: Ivan Ivanov
version: '1.0'
locale: ru # Язык по умолчанию
sites: [1, 2] # Доступно для сайтов. Если не указать, то будет доступно для всех сайтов.
license: MIT

description: Добро пожаловать в мир безграничных возможностей!
    | Тема представляет вам огромный ассортимент гибких настроек для создания великолепного адаптированного сайта с чистым и элегантным дизайном.
    | Благодаря HTML5 и CSS3 Вы получаете великолепный дизайн, красивые анимации и красивую главную страницу, заряженную слайдером, колонками,
    | полями для текстов и поддержкой шорткодов. Помимо всех редактируемых замечательных вещей,
    | Вы найдете избранные изображения, сокращенные сообщения, формат сообщений, Google шрифты, журнальный или блоговый режимы от ображения,
    | 8 зон для виджетов, поддержка переводов и многое другое!

regions: # Описание областей вывода в шаблонах, которые применяются в теме оформления.
    main_menu:
        title: Главное меню
        inheritance: [ 'root', 'main_menu' ] # Включить наследование в папках в случае автоматического создания областей.
    breadcrumbs: Хлебные крошки
    footer: Футер

modules: # Шаблоны для модулей
    Unicat:
        catalog: Каталог
        news: Новости
    Breadcrumbs:
        test: проверочный шаблон

structure: # Предлагать создать следующую структуру при установке на пустой сайт
    title: Главная
    children: # Служебный параметр в котором описываются внутренние разделы
        services:
            title: Услуги
            children:
                design: Дизайн
                seo: Продвижение
        news: Новости
        contacts: Контакты
        about: О компании
