version: '3.9'

services:
    mysql:
        image: mysql:8.0.27
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'cms'
            MYSQL_DATABASE: 'cms'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        ports:
            - '127.0.0.1:3996:3306'
        volumes:
            - mysql:/var/lib/mysql
        
volumes:
    mysql:
